{% set version = '2.1.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-piecewisesem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/piecewiseSEM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/piecewiseSEM/piecewiseSEM_{{ version }}.tar.gz
  sha256: d06405d6f3089a674a87468347e700f0c726edb7930531d24b3e0378fd1cf4b6

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-diagrammer
    - r-mass
    - r-car
    - r-emmeans
    - r-igraph
    - r-lme4
    - r-nlme
  run:
    - r-base
    - r-diagrammer
    - r-mass
    - r-car
    - r-emmeans
    - r-igraph
    - r-lme4
    - r-nlme

test:
  commands:
    - $R -e "library('piecewiseSEM')"           # [not win]
    - "\"%R%\" -e \"library('piecewiseSEM')\""  # [win]

about:
  home: https://github.com/jslefche/
  license: GPL-3
  summary: Implements piecewise structural equation modeling from a single list of structural
    equations, with new methods for non-linear, latent, and composite variables, standardized
    coefficients, query-based prediction and indirect effects. See <http://jslefche.github.io/piecewiseSEM/>
    for more.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: piecewiseSEM
# Type: Package
# Title: Piecewise Structural Equation Modeling
# Version: 2.1.0
# Date: 2019-12-05
# Authors@R: c( person("Jon", "Lefcheck",   role = c("aut", "cre"), email = "lefcheckj@si.edu"), person("Jarrett", "Byrnes",  role = "aut", email = "jarrett.byrnes@umb.edu"), person("James", "Grace",  role = "aut", email = "gracej@usgs.gov") )
# Maintainer: Jon Lefcheck <lefcheckj@si.edu>
# Description: Implements piecewise structural equation modeling from a single list of structural equations, with new methods for non-linear, latent, and composite variables, standardized coefficients, query-based prediction and indirect effects. See <http://jslefche.github.io/piecewiseSEM/> for more.
# Depends: R (>= 3.5.0)
# URL: https://github.com/jslefche/
# BugReports: https://github.com/jslefche/piecewiseSEM/issues
# Imports: car, DiagrammeR, emmeans, igraph, lme4, MASS, methods, nlme
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.0.2
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2019-12-05 16:02:47 UTC; jslef
# Author: Jon Lefcheck [aut, cre], Jarrett Byrnes [aut], James Grace [aut]
# Repository: CRAN
# Date/Publication: 2019-12-05 16:50:02 UTC
