{% set version = "2.3.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-piecewisesem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/piecewiseSEM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/piecewiseSEM/piecewiseSEM_{{ version }}.tar.gz
  sha256: 02969dca9fdeecf429c2882444ec74face8d4dfd2094da982851c582ae513e38

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base >=4.2.0
    - r-car
    - r-diagrammer
    - r-emmeans
    - r-igraph
    - r-lme4
    - r-mass
    - r-multcomp
    - r-mumin
    - r-nlme
    - r-performance
  run:
    - r-base >=4.2.0
    - r-car
    - r-diagrammer
    - r-emmeans
    - r-igraph
    - r-lme4
    - r-mass
    - r-multcomp
    - r-mumin
    - r-nlme
    - r-performance

test:
  commands:
    - $R -e "library('piecewiseSEM')"           # [not win]
    - "\"%R%\" -e \"library('piecewiseSEM')\""  # [win]

about:
  home: https://jslefche.github.io/piecewiseSEM/
  dev_url: https://github.com/jslefche/piecewiseSEM/
  doc_url: https://jslefche.github.io/piecewiseSEM/reference/index.html
  license: GPL-3.0-only
  summary: Implements piecewise structural equation modeling from a single list of structural equations, with new methods for non-linear, latent, and composite variables, standardized coefficients, query-based prediction and indirect effects. See <http://jslefche.github.io/piecewiseSEM/> for more.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
