{% set version = "2.1.0" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-piecewisesem
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/piecewiseSEM_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/piecewiseSEM/piecewiseSEM_{{ version }}.tar.gz
  sha256: d06405d6f3089a674a87468347e700f0c726edb7930531d24b3e0378fd1cf4b6

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip  # [win]
  host:
    - r-base
    - r-mass
    - r-car
    - r-lme4
    - r-nlme
    - r-pbkrtest
  run:
    - r-base
    - r-mass
    - r-car
    - r-lme4
    - r-nlme
    - r-pbkrtest

test:
  commands:
    - $R -e "library('piecewiseSEM')"  # [not win]
    - "\"%R%\" -e \"library('piecewiseSEM')\""  # [win]

about:
  home: https://github.com/jslefche/
  license: GPL-3.0
  summary: Implements piecewise structural equation modeling from a single list of structural
    equations, with new methods for non-linear, latent, and composite variables, standardized
    coefficients, query-based prediction and indirect effects. See <http://jslefche.github.io/piecewiseSEM/>
    for more.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
