travis:
  secure:
    BINSTAR_TOKEN: jf488LqxFdhZ1YcbV5NnqMadNKWjkEdl6nEEKy/pLM4hZqlc6Q1xzGS2rpx+oMNJL2cf2FbXkqWrR+VtKgwzLazIJzcRJt46+qwGZl+steGzZCtQDPY/2v7uOPRuSju6UxQHcQ4SQvo1KcoMY/5liJ0hvJDOzza+VfeecBI4bCI9FpeVveLnPjQKXsBG2C9u0AzBmTDR4vfZmlOcWIAhLrOM65XKa7I/WPkKRoU6BS/1WQB8yFcknyNdCC1dCk36Np1+ZUp7KsFdXpiTsMqotqjtRM/T7ZNQ1mvTa4e7+ydT3PiKUnmbW+2mBY1EBU20MM+lWbnA8hsPhT0nZSHKIyyZv0/UtGGSFFbLFNCH3dOvfxfMs8SNtzLEFTmDVgvO/NFj6+WLXqCINJtsXx0GIVp+DhffLL8rd8glyAJ1Fsn1X6oxJW+F4o56odeXiS2BkUUKf0BsigwtFtBMVRN4OMxvSntmp6vHifGuxtBeWxjKJdjGRPQpU8v0GpkGTnOu5MEHX4K0DuEiQmG5JJ83uc9w6IaWGx49KXl3bp/3hcvy03k1i4EDOMxWqEj/rXcukipGJVCXqh6KW2Y9NJpK6THke0wnpn0PpYhDX/pvSmKC73Zw31KkaGKcQDNMvWa9exj5lro6e9A9HeAtTFT4aU8VBeEHJpJ7q/Ul4t083BQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
